#!/usr/bin/env python3
import colorsys
import json
import re
import statistics
import sys
from io import BytesIO
from pathlib import Path
from urllib.request import Request, urlopen

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "src" / "product-catalog-odyssee-imported.js"
CACHE_PATH = ROOT / ".cache" / "imported-color-labels.json"


def load_catalog():
    source = CATALOG_PATH.read_text(encoding="utf-8")
    products_match = re.search(
        r"export const odysseeImportedProducts = ([\s\S]*?);\n\nexport const odysseeImportFailures = ",
        source,
    )
    failures_match = re.search(r"export const odysseeImportFailures = ([\s\S]*?);\n", source)
    if not products_match or not failures_match:
        raise RuntimeError("Cannot parse generated catalog")

    products_json = products_match.group(1).replace("Number.MAX_SAFE_INTEGER", "9007199254740991")
    failures_json = failures_match.group(1).replace("Number.MAX_SAFE_INTEGER", "9007199254740991")
    return json.loads(products_json), json.loads(failures_json)


def dump_catalog(products, failures):
    source = (
        "// Generated by scripts/import-odyssee-catalog.mjs\n"
        "// Do not edit manually; update the importer/source list and rerun it.\n\n"
        f"export const odysseeImportedProducts = {json.dumps(products, ensure_ascii=False, indent=2)};\n\n"
        f"export const odysseeImportFailures = {json.dumps(failures, ensure_ascii=False, indent=2)};\n"
    )
    CATALOG_PATH.write_text(source, encoding="utf-8")


def load_cache():
    if not CACHE_PATH.exists():
        return {}
    try:
        return json.loads(CACHE_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def save_cache(cache):
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CACHE_PATH.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")


def image_url(colorway):
    main_image = colorway.get("mainImage") or {}
    if main_image.get("assetUrl"):
        return main_image["assetUrl"]
    images = colorway.get("images") or []
    return (images[0] or {}).get("assetUrl") if images else ""


def dominant_rgb(url):
    request = Request(url, headers={"User-Agent": "Mozilla/5.0 (compatible; ODC color importer)"})
    with urlopen(request, timeout=15) as response:
        image = Image.open(BytesIO(response.read())).convert("RGB")

    image.thumbnail((96, 96))
    pixels = list(image.getdata())
    if not pixels:
        return (128, 128, 128)

    # Ignore near-white backgrounds and very dark shadows so product texture drives the label.
    filtered = []
    for r, g, b in pixels:
        mx = max(r, g, b)
        mn = min(r, g, b)
        if mx > 242 and (mx - mn) < 12:
            continue
        if mx < 22:
            continue
        filtered.append((r, g, b))

    pixels = filtered or pixels
    return tuple(int(statistics.median(channel)) for channel in zip(*pixels))


def classify_color(rgb):
    r, g, b = [value / 255 for value in rgb]
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    hue = h * 360
    red, green, blue = rgb
    warmth = red - blue

    if s < 0.12:
      if v < 0.20:
          return "Noir"
      if v < 0.34:
          return "Anthracite"
      if v < 0.58:
          return "Gris"
      if warmth > 12 and green >= blue:
          return "Grège"
      if v < 0.82:
          return "Gris clair"
      return "Blanc cassé"

    if s < 0.25 and 28 <= hue <= 65:
        if v < 0.45:
            return "Taupe"
        if v < 0.72:
            return "Lin"
        return "Beige"

    if hue < 16 or hue >= 345:
        return "Bordeaux" if v < 0.55 else "Rouge"
    if hue < 30:
        return "Terracotta" if v < 0.72 else "Rouille"
    if hue < 48:
        return "Camel" if v < 0.62 else "Ocre"
    if hue < 68:
        return "Moutarde" if s > 0.35 else "Sable"
    if hue < 155:
        return "Vert forêt" if v < 0.45 else "Vert sauge"
    if hue < 195:
        return "Bleu canard"
    if hue < 245:
        return "Bleu nuit" if v < 0.45 else "Bleu"
    if hue < 285:
        return "Violet"
    if hue < 345:
        return "Rose poudré" if v > 0.62 else "Prune"
    return "Naturel"


def is_numeric_label(value):
    return bool(re.fullmatch(r"\d+[A-Z]?", str(value or "").strip(), re.IGNORECASE))


def has_numeric_color_code(colorway):
    label = str(colorway.get("label") or "").strip()
    sku = str(colorway.get("sku") or "").strip()
    return is_numeric_label(label) or bool(re.search(r"(?:[-\s])\d+[A-Z]?$", sku, re.IGNORECASE))


def update_description(description, color_name):
    if not description:
        return description
    return re.sub(
        r"(<strong>Couleur:</strong>\s*)([^<]+)",
        lambda match: f"{match.group(1)}{color_name}",
        description,
        count=1,
    )


def main():
    products, failures = load_catalog()
    cache = load_cache()
    changed = 0

    for product in products:
        if product.get("brand") not in {"Froca", "Symphony Mills"}:
            continue

        for colorway in product.get("colorways") or []:
            if not has_numeric_color_code(colorway):
                continue

            url = image_url(colorway)
            if not url:
                continue

            if url not in cache:
                try:
                    cache[url] = classify_color(dominant_rgb(url))
                except Exception as exc:
                    print(f"warn: cannot classify {url}: {exc}", file=sys.stderr)
                    continue

            color_name = cache[url]
            colorway["label"] = color_name
            colorway["description"] = update_description(colorway.get("description", ""), color_name)

            for image_data in colorway.get("images") or []:
                image_data["title"] = color_name
            if colorway.get("mainImage"):
                colorway["mainImage"]["title"] = color_name
            changed += 1

    dump_catalog(products, failures)
    save_cache(cache)
    print(f"Updated {changed} numeric color labels")


if __name__ == "__main__":
    main()
